version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: nginx
    volumes:
      - ../build/:/app
      - ./default.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "80:80"
